### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by akiraOOyuu** [akiraOOyuu/protospace-39146#1]
#URL
https://protospace-39146.onrender.com

**Comment by shodai-ito** [comment]
@akiraOOyuu さん、ご提出ありがとうございます。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします。

[修正依頼箇所]
### **`ユーザー管理機能`**
- [x] **ログイン状態では、ヘッダーに「ログアウト」「New Proto」のリンクが存在すること**
ログインした状態でも、ヘッダーに「新規登録」「ログイン」のリンクが表示されたままになっています。
ログイン中に表示されるリンクが「ログアウト」「New Proto」のみになるよう実装しましょう。

- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
敬称が略されておりましたので、追記をお願いします。

### **`プロトタイプ投稿機能`**
- [x] **コンセプトの情報が必須であること**
コンセプト情報がなくても投稿できてしまいます。

### **`プロトタイプ一覧表示機能`**
- [x] **ログイン・ログアウトの状態に関わらず、プロトタイプ一覧を閲覧できること**
ログアウト状態でトップページを閲覧することができません。

- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
プロトタイプ名をクリックしても詳細ページに遷移できません。
画像と同様、プロトタイプ名にもリンクを設定してください。

### **`コメント機能`**
- [x] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
コメントフォームを空の状態で投稿すると、エラー画面になってしまいます。

### **`ユーザー詳細機能`**
- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
一部ユーザー名が正しく表示されておりません。
<img width="640" alt="スクリーンショット 2023-06-07 9 39 24" src="https://github.com/akiraOOyuu/protospace-39146/assets/62537107/458be588-99aa-4a74-9da2-d1f7d461ae2a">

### **`その他`**
- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他人のプロトタイプも編集できてしまいます。
【チェック方法】
先ず、ユーザーAで投稿したプロトタイプの編集ページURLをコピー。
次に、ユーザーBでログインし、そのURLを直接入力した際に、トップページへリダイレクトされれば正常な挙動。

修正が完了しましたら、**一度ご自身の本番環境で正しく動作しているか確認**してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by shodai-ito** [comment]
@akiraOOyuu さん、再度ご提出ありがとうございます‼︎
上記指摘内容の修正が確認できました。
引き続き動作の確認をしたところ、新たに修正いただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **コメントを投稿すると、投稿したコメントとその投稿者名が、対象プロトタイプの詳細ページにのみ表示されること**
ログアウト状態になると、詳細ページのコメントが全て非表示になってしまいます。
ログイン状態に関わらず、コメントは常に表示されるよう実装お願いします。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by motomuun** [comment]
@akiraOOyuu さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
